name: inconvenientdesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60431
title: inconvenientdesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#d18815'
    - '#4b3013'
    - '#d1cecc'
  brandStrength: 0.009364976081997156
  lightness: 0.11890828097239137
  saturation: 0.5980715919286013
  rhythmicContrast: 0.5340426668990403
purpose: []
